namespace: jasonlearst
name: pihole
version: "1.2.0"
readme: README.md
authors:
  - Shane Barbetta
  - Jason Learst
description: >
  A collection of modules for managing your Pi-hole installation. Fork with performance optimizations and TTL handling improvements.
license:
  - "MIT"
tags:
  - pihole
  - dns
  - networking
dependencies: {}
repository: https://github.com/jasonlearst/pihole-ansible
